### PR TITLE
enabling rali to give fp16 output tensors

### PR DESCRIPTION
**Pull request by LakshmiKumar23**

### CODE REVIEW

**Comment by LakshmiKumar23** [comment]
@Reza-Najafi Ready to be merged after you test rali_torch

**Review by Reza-Najafi — COMMENTED** [review]
Can we use an enumerator in the Python API, instead of a boolean for FP16, we could have more data types to support, we can call it TensorDataType , similar to TensorLayout

**Review by Reza-Najafi — COMMENTED** [review]
Please change the self.FP16  to self.tensor_dtype in all iterator classes

**Review by Reza-Najafi — COMMENTED** [review]
please make all enum values explicitly set to integer equivalents

**Comment by LakshmiKumar23** [comment]
Will fix and create again

**Pull request closed without merging**
